# Site settings
title: Browser Security Enhancements Tracker
companytitle: NotSoSecure
email: info@notsosecure.com
description: > # this means to ignore newlines until "baseurl:"
  The browsers are currently implementing lots of changes day by day. We will be listing changes relevant to security enhancements which known browsers have implemented recently. Such security updates are aimed to be updated on regular intervals.
baseurl: "/browser-security-enhancements/" # the subpath of your site, e.g. /blog
url: "https://notsosecure.github.io" # the base hostname & protocol for your site
companyurl: "https://www.notsosecure.com"
twitter_username: notsosecure
github_username:  notsosecure

# Build settings
markdown: kramdown
future: true

# credit-name1: Akshay Sudan
# credit-link1: https://twitter.com/akshay_asc11

# credit-name2: Dharmendra Gupta
# credit-link2: https://twitter.com/ItsDg4u

# credit-name3: Savan Gadhiya
# credit-link3: https://twitter.com/gadhiyasavan
permalink: /:title:output_ext